agents:
  queue: "${QUEUE-default}"

steps:
  - label: ":rocket: Push to :kubernetes:"
    command: script/buildkite/deploy
    concurrency: 1
    concurrency_group: deploy/tutorial
    agents:
      queue: "nutrien-sanbox-au"


