---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buildkite-demo
  labels:
    app: buildkite-demo
spec:
  # TODO: replace with a value that fits your application
  replicas: 3
  selector:
    matchLabels:
      app: buildkite-demo
  template:
    metadata:
      labels:
        app: buildkite-demo
    spec:
      containers:
        - name: app
          image: "${DOCKER_IMAGE}"
          ports:
            # TODO: replace with the correct port for your application
            - containerPort: 3000